"""empty message

Revision ID: 9b9e18bb23ee
Revises: a11c4510b972
Create Date: 2024-05-13 17:35:24.726063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9e18bb23ee'
down_revision: Union[str, None] = 'a11c4510b972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'create_date')
    # ### end Alembic commands ###
